### PR TITLE
Fix keyboard shortcuts not working in REI recipe overlay screens

### LINKED ISSUE #130: Ability to use BZ/AH search button inside REI recipe viewer
### Describe the feature

Could be nice if you could use bazzar/ah search button inside REI recipe viewer (you can do that on REI panes but not inside rei recipe viewer somehow)

Image

### Other mods

_No response_

### PR DESCRIPTION
**Pull request by einekratzekatze**
HandledScreenKeyPressedEvent was not being published when REI's usage/recipe overlay was open, causing features like ItemHotkeys to not work. Added a mixin to publish the event when REI's ScreenOverlayImpl handles key input. The current implementation gives REI priority for Keybinds.

Co-Authored-By: Claude Sonnet 4.5 <noreply@anthropic.com>
As this is AI Code please review it carefully. I reviewed it myself, but I do not have knowledge of the underlying systems (mixins (other than the core concept), key press processing by Minecraft, REI or Firmament and how Minecraft screens work)

Fixes #130

### CODE REVIEW

File: src/compat/rei/java/moe/nea/firmament/mixins/compat/PublishREIOverlayKeyPressEvent.java [hunk 1]
```diff
@@ -0,0 +1,36 @@
...
+import org.spongepowered.asm.mixin.injection.At;
+import org.spongepowered.asm.mixin.injection.Inject;
+import org.spongepowered.asm.mixin.injection.callback.CallbackInfoReturnable;
+
+/**
+ * Publishes HandledScreenKeyPressedEvent for the REI overlay screen.
+ * This ensures that keyboard shortcuts work even when viewing REI recipe/usage screens.
+ * Fires AFTER REI processes the key, so REI's built-in shortcuts take priority.
+ */
+@Mixin(targets = "me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl")
```
Comment (lineargraph) [inline src/compat/rei/java/moe/nea/firmament/mixins/compat/PublishREIOverlayKeyPressEvent.java:20]: if prefer to compile directly against class names rather than with pseudo

**Review by lineargraph — COMMENTED** [review]
perhaps at this point it would make more sense to have a generic screen key handler. but unfortunately we dont want to handle keypresses on every screen (think pause screen, for example), and handledscreen is the best litmus test. worth a consideration either way to move that list of enabled screens into to be an explicit check rather than just where we put the mixin.

File: src/compat/rei/java/moe/nea/firmament/mixins/compat/PublishREIOverlayKeyPressEvent.java (hunk 1 above)
Comment (einekratzekatze) [reply src/compat/rei/java/moe/nea/firmament/mixins/compat/PublishREIOverlayKeyPressEvent.java:20]: I thought that isnt possible, ill check it out

**Comment by einekratzekatze** [comment]
> perhaps at this point it would make more sense to have a generic screen key handler. but unfortunately we dont want to handle keypresses on every screen (think pause screen, for example), and handledscreen is the best litmus test. worth a consideration either way to move that list of enabled screens into to be an explicit check rather than just where we put the mixin.

Seems like the better approach for sure. Do other screens with this issue come to mind? If so it should probably be done this way, but that's not something id like to/should do.
