### PR TITLE
fix: prevent sending ServerboundPartyInfoPacket when not on Hypixel, as other Servers/World cant handle it. 

### LINKED ISSUE #2291: Game saves and quits out of singleplayer world when switching between dimensions
### Firmament Version

Firmament 44.0.1+mc1.21.11

### Bug Description

When switching between dimensions in a singleplayer world I get kicked to the title screen with this error Internal Exception: io.nettg.handler.codec.OecoderException: railed to decode packet

[latest log.txt](https://github.com/user-attachments/files/26324741/latest.log.txt)

### Minecraft Log

```plain text

```

### PR DESCRIPTION
**Pull request by einekratzekatze**
Fixes #2291

### CODE REVIEW

**Comment by lineargraph** [comment]
Hello, sorry to bother you and I don't want to be accusatory (ill be asking all creatures submitting PRs) can you declare whether or not you used AI to author these changes? If so it would be nice if you could tag Claude (or whatever AI you were using) as a coauthor so I can keep better track of AI generated changes. If not just tell me and ill do that tagging during rebasing.

File: src/main/kotlin/util/skyblock/PartyUtil.kt [hunk 1]
```diff
@@ -37,7 +38,7 @@ object PartyUtil {
 			}
 		}
 
-		fun sendSyncPacket() {
+		fun sendSyncPacket() { if (!SBData.isOnHypixel) return
```
Comment (lineargraph) [inline src/main/kotlin/util/skyblock/PartyUtil.kt]: come on we can at least run a formatter on this lmao

**Review by lineargraph — APPROVED** [review]
